name: Metrics

on:
  schedule:
    - cron: "0 0 * * *"   # once a day at midnight UTC
  workflow_dispatch:      # Allows manual runs

permissions:
  contents: write

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Metrics embed
        uses: lowlighter/metrics@v3.34
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          base: header, activity, repositories, metadata
          plugin_introduction: yes
          plugin_contributors: yes
          plugin_languages: yes
          plugin_languages_limit: 12
          plugin_languages_sections: most-used
          plugin_achievements: yes
          plugin_achievements_only: >- 
            polyglot, stargazer, sponsor, deployer, member, maintainer, developer,
            scripter, packager, explorer, infographile, manager
          plugin_achievements_display: compact
          plugin_calendar: yes
          plugin_calendar_limit: 3
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
